title: "selfdriven Insure"
description: "Conceptual frameworks for decentralised human/purpose driven community risk-sharing/insurance."
baseurl: ""
url: ""
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: selfdriven
plugins:
  - jekyll-feed
  - jekyll-seo-tag
